### ISSUE TITLE
With Django 5.0, calling `choices` is optional, this lib should behave similary.

### ISSUE THREAD

**Issue by Alexerson** [MaxDude132/django-register-field#29] opened 2024-01-04 22:55 UTC
Right now the iterator on the choice field returns the items, not the choices.

**Comment by MaxDude132** [comment] 2024-01-08 14:42
Agreed, now that Django 5.0 is out, we should adapt the behaviour. Looking into it.

**Comment by MaxDude132** [comment] 2024-01-08 15:00
This is already the behaviour, as the choices are built dynamically from the object. The `__iter__` of the `RegisterChoices` has to return the items, because that is the way we iterate through (though we could change that if needed). Currently, I do not see the need for any changes, other than adapting the tests to show this works. I do not think there is really an issue, @Alexerson can you show a problem you had? Removing `.choices` in the tests worked fine right away without any finessing.

**Comment by MaxDude132** [comment] 2024-01-08 15:04
See attached branch for change in the tests.

**Comment by MaxDude132** [comment] 2024-01-08 15:28
Looking at the code for Django 5.0, the choices are not handled in the `__iter__` (which still returns the enum items), but rather by the Field, which is also how I went about implementing it. This means that iterating over the choices outside the fields gives the items as you would expect, but you still do not need to add `.choices` when passing it to the field. This is expected behaviour. I will close the issue for now, let me know if you find a situation that does not work for you and I will reopen it.

**Comment by MaxDude132** [comment] 2024-01-08 16:14
Alright after more testing, there is indeed an issue. I think it's a one-liner though, I'll look into it

**Closed** 2024-01-08 16:36 UTC

**Comment by Alexerson** [comment] 2024-01-08 16:38
All good!
